version: '3.4'

services:
  mongo:
    container_name: mongodb
    image: mongo:latest
    env_file:
      - .env
    environment:
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DATA_DIR=/data/db
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    volumes:
      - mongo:/data/db
    networks:
      - common_network

  app:
    container_name: nest-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - NEST_PORT=${NEST_PORT}
    ports:
      - '${NEST_PORT}:${NEST_PORT}'
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - common_network

networks:
  common_network:
    driver: bridge

volumes:
    mongo:
      external: false
